version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ./.docker/ssh
  webssh.cyrhades.fr:
    build: ./.docker/webssh
    ports:
      - ${PORT}:8888
  keykoolol.cyrhades.fr:
    image: anssi/fcsc2020-reverse-keykoolol:latest
    ports:
      - "4000:4000"
